### ISSUE TITLE
Containment Chalice don't work after installing this

### ISSUE THREAD

**Issue by Helium8** [qiyuan11111/Astral_Patch#1]
I am playing [Enigtech2](https://github.com/ET-Team/EnigTech2) recently. After installing this mod the Containment Chalice don't work.

**Comment by qiyuan11111** [comment]
This mod is out-of-dated. 

> I am playing [Enigtech2](https://github.com/ET-Team/EnigTech2) recently. After installing this mod the Containment Chalice don't work.

This mod is out-of-date. No maintenance in the short term. Sorry!

**Comment by Helium8** [comment]
ok, thank you for reply😊
